# Generated by Django 5.1 on 2024-08-20 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_record"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
